// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHiSBLtL-YxQU71Ef4eI0YIUXm2S_N-EA',
    appId: '1:19979470087:web:32e9119a08915358e6f1a2',
    messagingSenderId: '19979470087',
    projectId: 'activity14-fcm-ea905',
    authDomain: 'activity14-fcm-ea905.firebaseapp.com',
    storageBucket: 'activity14-fcm-ea905.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKeVrw9iRcZD3_nqzpcKKjl4yCxgNWVGo',
    appId: '1:19979470087:android:075d8b2259e5b68ae6f1a2',
    messagingSenderId: '19979470087',
    projectId: 'activity14-fcm-ea905',
    storageBucket: 'activity14-fcm-ea905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdIrvVIMwiHoowScvoKTfbHxSH977dK0U',
    appId: '1:19979470087:ios:5e8f44d7c45d2cbfe6f1a2',
    messagingSenderId: '19979470087',
    projectId: 'activity14-fcm-ea905',
    storageBucket: 'activity14-fcm-ea905.firebasestorage.app',
    iosBundleId: 'com.example.activity14Fcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdIrvVIMwiHoowScvoKTfbHxSH977dK0U',
    appId: '1:19979470087:ios:5e8f44d7c45d2cbfe6f1a2',
    messagingSenderId: '19979470087',
    projectId: 'activity14-fcm-ea905',
    storageBucket: 'activity14-fcm-ea905.firebasestorage.app',
    iosBundleId: 'com.example.activity14Fcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHiSBLtL-YxQU71Ef4eI0YIUXm2S_N-EA',
    appId: '1:19979470087:web:5b695bff580394cae6f1a2',
    messagingSenderId: '19979470087',
    projectId: 'activity14-fcm-ea905',
    authDomain: 'activity14-fcm-ea905.firebaseapp.com',
    storageBucket: 'activity14-fcm-ea905.firebasestorage.app',
  );
}
